image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  - mkdir -p public/.well-known/acme-challenge/
  - echo FG8ijZbrLi5-8gkJ6XFe_QuYVqS7uT-l_Sb6zDqDiOI.9R2ot3E7Mhp2vsitv7KTRdriVjHg7MgybtbDDa9cw7Q > public/.well-known/acme-challenge/FG8ijZbrLi5-8gkJ6XFe_QuYVqS7uT-l_Sb6zDqDiOI
  artifacts:
    paths:
    - public
  only:
  - master

  artifacts:
    paths:
    - public
  only:
  - master
